<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.admin_index_module_photo}                        
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_total_photo}                        
        </td>
        <td>
        	{$photoStatistics_arr.total_active_photo}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_activate_photo}                        
        </td>
        <td>
        	{$photoStatistics_arr.total_toactivate_photo}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_today_new_photo}                        
        </td>
        <td>
        	{$photoStatistics_arr.total_today_photo}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_week_photo}                        
        </td>
        <td>
        	{$photoStatistics_arr.this_week_photo}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_month_photo}                        
        </td>
        <td>
       		{$photoStatistics_arr.this_month_photo}                        
        </td>
    </tr>
</table>