<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.admin_index_module_article}
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_total_article}
        </td>
        <td>
        	{$articleStatistics_arr.total_active_article}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_activate_article}
        </td>
        <td>
        	{$articleStatistics_arr.total_toactivate_article}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_today_new_article}
        </td>
        <td>
        	{$articleStatistics_arr.total_today_article}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_week_article}
        </td>
        <td>
        	{$articleStatistics_arr.this_week_article}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_month_article}
        </td>
        <td>
       		{$articleStatistics_arr.this_month_article}
        </td>
    </tr>
</table>