<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.admin_index_module_video}                        
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_total_video}                        
        </td>
        <td>
        	{$videoStatistics_arr.total_active_video}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_activate_video}                        
        </td>
        <td>
        	{$videoStatistics_arr.total_toactivate_video}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_today_new_video}                        
        </td>
        <td>
        	{$videoStatistics_arr.total_today_video}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_week_video}                        
        </td>
        <td>
        	{$videoStatistics_arr.this_week_video}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_month_video}                        
        </td>
        <td>
       		{$videoStatistics_arr.this_month_video}                        
        </td>
    </tr>
</table>