<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.admin_index_module_music}                        
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_total_music}                        
        </td>
        <td>
        	{$musicStatistics_arr.total_active_music}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_activate_music}                        
        </td>
        <td>
        	{$musicStatistics_arr.total_toactivate_music}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_today_new_music}                        
        </td>
        <td>
        	{$musicStatistics_arr.total_today_music}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_week_music}                        
        </td>
        <td>
        	{$musicStatistics_arr.this_week_music}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_month_music}                        
        </td>
        <td>
       		{$musicStatistics_arr.this_month_music}                        
        </td>
    </tr>
</table>