<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.discussions}
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_total_boards}
        </td>
        <td>
        	{$discussionStatistics_arr.total_boards}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_todays_boards}
        </td>
        <td>
        	{$discussionStatistics_arr.todays_boards}
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_todays_solutions}
        </td>
        <td>
        	{$discussionStatistics_arr.todays_solutions}
        </td>
    </tr>
</table>