<table class="">
    <tr>
        <th colspan="2">
        	{$LANG.admin_index_module_blog}                        
        </th>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_total_blog}                        
        </td>
        <td>
        	{$blogStatistics_arr.total_active_blog}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_activate_blog}                        
        </td>
        <td>
        	{$blogStatistics_arr.total_toactivate_blog}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_today_new_blog}                        
        </td>
        <td>
        	{$blogStatistics_arr.total_today_blog}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_week_blog}                        
        </td>
        <td>
        	{$blogStatistics_arr.this_week_blog}                        
        </td>
    </tr>
    <tr>
        <td>
        	{$LANG.admin_index_this_month_blog}                        
        </td>
        <td>
       		{$blogStatistics_arr.this_month_blog}                        
        </td>
    </tr>
</table>